=== lisacsn/inf3190_tp2/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- DÃ©finition d'un historique de manifestations -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="historique">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="greve" minOccurs='1' maxOccurs='unbounded'>
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="datedebut" type="xs:date"/>
                    <xs:element name="datefin" type="xs:date"/>
                    <xs:element name="cause" type="xs:string"/>
                </xs:sequence> 
            </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== lisacsn/inf3190_tp2/historique.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="affichage.xsl"?>

<historique xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="schema.xsd">
    <greve>
        <datedebut>2017-09-24</datedebut>
        <datefin>2017-09-29</datefin>
        <cause>Flemme de travailler c'est la rentr√©e</cause>
    </greve>
    
    <greve>
        <datedebut>2018-04-11</datedebut>
        <datefin>2018-05-02</datefin>
        <cause>Mon patron fait plus de moula que moi</cause>
    </greve>
    
    <greve>
        <datedebut>2019-11-13</datedebut>
        <datefin>2019-11-14</datefin>
        <cause>Ammar Hammad</cause>
    </greve>
</historique>
